name: PR Size Alert

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-pr-size:
    runs-on: ubuntu-latest
    env:
      # Set your line change threshold here
      THRESHOLD: 500 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Calculate PR Size
        id: pr-size
        uses: ./.github/actions/pr-size-calculator
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ github.event.pull_request.number }}
          threshold: ${{ env.THRESHOLD }}

      - name: Send Slack Alert
        uses: ./.github/actions/pr-alert-on-slack
        with:
          exceeds_threshold: ${{ steps.pr-size.outputs.exceeds_threshold }}
          total_changes: ${{ steps.pr-size.outputs.total_changes }}
          pr_url: ${{ github.event.pull_request.html_url }}
          pr_number: ${{ github.event.pull_request.number }}
          actor: ${{ github.actor }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send Email Alert
        uses: ./.github/actions/pr-alert-on-mail
        with:
          exceeds_threshold: ${{ steps.pr-size.outputs.exceeds_threshold }}
          total_changes: ${{ steps.pr-size.outputs.total_changes }}
          pr_url: ${{ github.event.pull_request.html_url }}
          pr_number: ${{ github.event.pull_request.number }}
          actor: ${{ github.actor }}
          smtp_username: ${{ secrets.SMTP_USERNAME }}
          smtp_password: ${{ secrets.SMTP_PASSWORD }}
          alert_email_to: dev-team-alerts@yourcompany.com
